### ISSUE TITLE
Seeing `tesseract - read_params_file: Can't open ...` in the logs

### ISSUE THREAD

**Issue by nkrot** [stefan6419846/tesstrain_package#9]
Hello

I have been running `tesstrain` tool and seen it printing lines like this to the log file:

```
[2024-03-26 02:01:39,355] - DEBUG - tesseract - read_params_file: Can't open /path/to/tessdata_best/configs/
````

The directory exists (it is TESSDATA_PREFIX). The message is not an error, the script continues running and completes successfully. The message is however misleading, it makes me think something is wrong. Would it be possible to silence it?

The above message is generated when this line https://github.com/stefan6419846/tesstrain_package/blob/e399320c6f206aeb2039bfee5859988d8043f193/tesstrain/generate.py#L313 has a value of empty string

```
            future = executor.submit(
                run_command,
                "tesseract",
                img_file,
                pathlib.Path(img_file).with_suffix(""),
                *box_config,
                config,   # <-- this is "" and causes a message being printed
                env=tessdata_environ,
            )
```

Best regards,
Nikolai

**Comment by stefan6419846** [comment]
This message originates from the Tesseract subprocess, not from *tesstrain* itself. I do not think that we should filter any of the output. Some people might consider this message useful, others not.

**Comment by stefan6419846** [comment]
Should be fixed. As this is some nitpick, I am not doing a dedicated release for it now.
